# Export-PrecheckRoleAssignmentScript
# Writes a ready-to-review PowerShell script that re-creates this Windows server's
# console role assignments ON THE APPLIANCE, in the form the appliance requires.
#
# Why this exists. A Windows VBR normalises every domain principal to DOMAIN\user -
# entering user@fqdn and reopening the dialog gives DOMAIN\user back - while the
# appliance sign-in accepts only user@fqdn. The assignments therefore cannot be
# prepared on the source, and KB4800 places the work after the migration. Doing it by
# hand means retyping every assignment on every server in the estate, which is where
# the transcription errors come from.
#
# THIS FUNCTION WRITES A TEXT FILE. It never executes anything and never changes this
# server. The generated script is meant to be READ, then run on the appliance by an
# operator signed in as veeamadmin.
#
# Note for anyone editing: the generated commands are assembled from a variable so
# that no Veeam write cmdlet appears at the start of a line in THIS file - the build
# tests assert the shipped artefact contains none, which is how the tool's read-only
# guarantee is enforced.

function Export-PrecheckRoleAssignmentScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $Path,
        $Context
    )

    if (-not (Test-PrecheckCmdlet 'Get-VBRUserRoleAssignment')) { return $null }

    $assignments = @()
    try {
        $assignments = @(Get-PrecheckCached -Key 'RoleAssignments' -Getter { Get-VBRUserRoleAssignment -ErrorAction SilentlyContinue })
    } catch { return $null }
    if ($assignments.Count -eq 0) { return $null }

    # The domain this server belongs to, so NETBIOS\name can become name@fqdn. Same
    # resolution SEC-004 uses. Without it nothing can be converted automatically and
    # every line is emitted for the operator to complete by hand.
    $fqdn = $null
    try {
        $cs = Get-PrecheckCached -Key 'ComputerSystem' -Getter { Get-CimInstance Win32_ComputerSystem -ErrorAction Stop }
        if ($cs.PartOfDomain -and $cs.Domain) { $fqdn = [string]$cs.Domain }
    } catch { }
    if (-not $fqdn -and $env:USERDNSDOMAIN) { $fqdn = [string]$env:USERDNSDOMAIN }
    $shortDomain = if ($fqdn) { ($fqdn -split '\.')[0] } else { $null }

    $cmd       = 'Add-VBRUserRoleAssignment'
    $ready     = [System.Collections.Generic.List[string]]::new()
    $review    = [System.Collections.Generic.List[string]]::new()
    $already   = 0

    foreach ($ra in $assignments) {
        $name = [string]$ra.Name
        if (-not $name) { continue }
        $role = if ($ra.PSObject.Properties['Role'] -and $ra.Role) { [string]$ra.Role } else { 'BackupAdmin' }

        # Already in an appliance-acceptable form - nothing to re-create.
        if ($name -match '@') { $already++; continue }

        $prefix = if ($name -match '\\') { $name.Split('\')[0] } else { '' }
        $leaf   = if ($name -match '\\') { $name.Substring($name.IndexOf('\') + 1) } else { $name }

        # BUILTIN, NT AUTHORITY and machine-local principals have no counterpart on a
        # Linux appliance. There is no correct automatic answer - which domain principal
        # should inherit the role is a decision - so these are emitted commented out.
        $isLocal = ($prefix -match '^(BUILTIN|NT AUTHORITY)$') -or
                   ($prefix -and $env:COMPUTERNAME -and ($prefix -ieq $env:COMPUTERNAME))
        if ($isLocal) {
            $review.Add("# $name  [$role]")
            $review.Add("#   No counterpart on the appliance. Decide which DOMAIN principal should")
            $review.Add("#   hold this role, then uncomment and complete:")
            $review.Add("#   $cmd -Name '<user>@$(if ($fqdn) { $fqdn } else { '<domain>' })' -Role $role")
            $review.Add('')
            continue
        }

        # A NetBIOS prefix matching this server's own domain can be converted with
        # confidence. Anything else - another domain, an unknown prefix - cannot, so it
        # is emitted for completion rather than guessed.
        if ($prefix -and $shortDomain -and ($prefix -ieq $shortDomain) -and $fqdn) {
            $ready.Add("$cmd -Name '$leaf@$fqdn' -Role $role")
            continue
        }

        $review.Add("# $name  [$role]")
        $review.Add("#   Prefix '$prefix' is not this server's domain, so the correct suffix is not")
        $review.Add("#   known here. Complete and uncomment:")
        $review.Add("#   $cmd -Name '$leaf@<domain>' -Role $role")
        $review.Add('')
    }

    if ($ready.Count -eq 0 -and $review.Count -eq 0) { return $null }

    $server = if ($Context -and $Context.Server) { $Context.Server } else { $env:COMPUTERNAME }
    $out = [System.Collections.Generic.List[string]]::new()
    $out.Add('# Console role assignments to re-create on the Veeam Software Appliance.')
    $out.Add("# Generated by VbrMigrationPrecheck $(if ($script:PrecheckVersion) { $script:PrecheckVersion } else { '' }) from $server on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').")
    $out.Add('#')
    $out.Add('# READ THIS BEFORE RUNNING IT.')
    $out.Add('#')
    $out.Add('# Run this ON THE APPLIANCE, AFTER the migration, signed in as veeamadmin.')
    $out.Add('# KB4800 lists re-creating console access as a post-migration task. Creating these')
    $out.Add('# beforehand is unlikely to help: the migration injects the database, so anything')
    $out.Add('# already present would most likely be overwritten.')
    $out.Add('#')
    $out.Add('# Why it cannot be done on the Windows server: that console normalises every domain')
    $out.Add('# principal to DOMAIN\user and converts a user@fqdn entry straight back, while the')
    $out.Add('# appliance sign-in accepts only user@fqdn.')
    $out.Add('#')
    $out.Add('# Check every line against your own records before running. This was generated from')
    $out.Add('# what the source server held; it does not know which of those principals should')
    $out.Add('# still have access.')
    $out.Add('')
    if ($already -gt 0) {
        $out.Add("# $already assignment(s) on the source were already in an appliance-acceptable form")
        $out.Add('# and are not repeated here.')
        $out.Add('')
    }
    if ($ready.Count -gt 0) {
        $out.Add('# --- Ready to run ------------------------------------------------------------')
        foreach ($l in $ready) { $out.Add($l) }
        $out.Add('')
    }
    if ($review.Count -gt 0) {
        $out.Add('# --- Need a decision before they can be run ----------------------------------')
        foreach ($l in $review) { $out.Add($l) }
    }

    $out -join [Environment]::NewLine | Set-Content -Path $Path -Encoding UTF8
    return $Path
}
